### ISSUE TITLE
Doesn't work on ST3

### ISSUE THREAD

**Issue by seanhess** [raph-amiard/sublime-typescript#12]
Installed via git as per the instructions, when it loads, it pops up an error saying it can't find the syntax file for TypeScript.

**Comment by raph-amiard** [comment]
Hi sean, thanks for your feedback, and sorry for the long answer latency :)

The plugin won't work on Sublime Text 3, which is to be expected since Sublime Text 3 has a completely new API. I'm don't think i'll be porting the plugin. Given how often ST changes (API/pricing/etc) i'll wait and see how it evolves first.

Also, i don't think it would be possible to have a version that works on both. There would be a need to maintain two branches, and i'm not keen on that idea either.

**Comment by jordwalke** [comment]
Which parts of the Sublime API have changed that would make it difficult to update this plugin to the new Sublime version? I'd really like to see this work with ST3.
