### ISSUE TITLE
Possible Kickstart Project?

### ISSUE THREAD

**Issue by ghost** [raph-amiard/sublime-typescript#25]
Is there any chance I (and potentially others) can entice Raphael to put some more time into this project with some funding?

As someone who codes TypeScript for 12+ hours / day, I would drop $100 - $200 on this plugin without even thinking, but likely even more, if it:
- Supported the latest version of TypeScript.
- Supported the latest version of Sublime.
- Had safe refactor, find all references, and go to definition.
- Was relatively stable.

I would work on this myself, but I literally have zero time.

Takers?

**Comment by rictic** [comment]
I'd kick in some money too.

I recommend looking at BountySource rather than Kickstarter though, as they're better set up for this sort of thing. I funded a javascript implementation of git there for example: https://www.bountysource.com/fundraisers/325-js-git

**Comment by seanhess** [comment]
It's usually hard to motivate people that way though, isn't it? People don't do open source for the money.

**Comment by raph-amiard** [comment]
Hi all, and sorry for taking so long to answer this.

Unfortunately, i'm full time employed, and i have other priorities for my off job time, so the financial incentive is not terribly interresting for me.

This plugin is suffering from my lack of time, but it is not the only reason. Here are the others :
1. I don't program in typescript, not even one bit. I do find the language interesting, but i am not using it.
2. I don't use Sublime no more, probably never will. The only reason i did this plugin is because i didn't want to learn Vimscript in the first place.
3. Both TypeScript and Sublime Text are moving targets. Also, the API for TypeScript that i am using to provide completion is totally undocumented, and suffers from a big problem with handling imports (basically, it doesn't, that's why the current plugin only handle file refs via comments, because that's the only thing i was ok to do manually)
4. I didn't find a way to contact Typescript developpers to find answers about the aforementionned problem, which is a pretty big one.

If you solve this problem, the rest of it is just easy work, adapting the APIs and i must admit i'm quite surprised nobody is willing to give it a shot. I will be happy to help, i just can't lead the effort.

Contact me if anyone is interrested, not in giving money, but time for this project (for example contacting the TS developpers and asking them about the right approach to their IDE api).

In the meantime, i won't do any further development on this project. I will update the README so no one can get confused about that.

Thank you all :)

**Comment by raph-amiard** [comment]
Also @bunnycode, although i do believe you when you say you literally have zero time, i find it strange that if you code in Typescript 12 hours/day, you don't have the time to invest into creating yourself a proper coding environment.

It literally took me a couple days to create this plugin. I think with the same amount of time you could take it to where you want, and if you spend so much time coding in Typescript, it would probably be a worthy investment.

**Comment by Truebase-com** [comment]
Thanks for the update, I'm seriously considering it :)

**Comment by raph-amiard** [comment]
Ok well don't hesitate to ask me anything, i'll be glad to help, and even contribute if i can, i just can't afford to lead and maintain this project !

**Comment by seanhess** [comment]
I can help too, but I don't know enough python or about sublime to lead right now. If someone wants to pick up as the leader I'd be happy to pitch in 
—
